# Generated by Django 3.2.2 on 2021-05-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smarphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Имя категории',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notebook',
            name='diagonal',
            field=models.CharField(max_length=255, verbose_name='Диаганоль'),
        ),
    ]
