# Generated by Django 3.2.2 on 2021-05-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210525_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smarphone',
            new_name='Smartphone',
        ),
    ]
